---
# tasks file for couchdb-lucene
- name: download src
  become: yes
  become_user: root
  get_url:
    url: '{{couchdb_lucene_src_tgz_url}}'
    dest: /tmp/{{couchdb_lucene_src_tgz}}
    mode: 0644

- name: create parent srcs dir
  become: yes
  become_user: root
  file:
    path: '{{couchdb_lucene_parent_srcs_dir}}'
    state: directory
    mode: 0755
    
- name: unarchive
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{couchdb_lucene_src_tgz}}
    dest: '{{couchdb_lucene_parent_srcs_dir}}'
    mode: 0755
    creates: '{{couchdb_lucene_build_dir}}'

- name: build...
  become: yes
  become_user: root
  command: mvn
  args:
    chdir: '{{couchdb_lucene_build_dir}}'
    creates: '{{couchdb_lucene_install_tgz_path}}'

- name: install...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: '{{couchdb_lucene_install_tgz_path}}'
    dest: '{{couchdb_lucene_parent_install_dir}}'
    creates: '{{couchdb_lucene_parent_install_dir}}/{{couchdb_lucene_name}}'

- name: templatize/configure...
  become: yes
  become_user: root
  with_items:
    - f: couchdb-lucene.ini
      d: '{{couchdb_lucene_install_dir}}/conf'
      m: '0644'
    - f: log4j.xml
      d: '{{couchdb_lucene_install_dir}}/conf'
      m: '0644'
    - f: launch-couchdb-lucene
      d: '{{couchdb_lucene_parent_install_dir}}/bin'
      m: '0755'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
